name: Bot

on:
  issue_comment:
    types:
      - created

permissions:
  actions: write
  pull-requests: write

jobs:
  act:
    runs-on: ubuntu-latest
    steps:
      - uses: ahus1/keycloak-gh-actionbot@action-bot
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          debug: 'true'
