name: Bot

on:
  issue_comment:
    types:
      - created

permissions:
  actions: write
  pull-requests: write

jobs:
  act:
    runs-on: ubuntu-latest
    steps:
      - uses: keycloak/keycloak-gh-actionbot@33d8759517f1bfbb70d52fa1f6d58ef2e824301b # v0.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          debug: 'true'
